spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/votingsession}
      auto-index-creation: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

clients:
  user-info:
    url: https://user-info.herokuapp.com/